---
title: "EDA"
author: "Weijia Xiong"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## data
```{r load data, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),  # download weather data
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%   #floor_date() takes a date-time object and rounds it down to the nearest boundary of the specified time unit.
  select(name, id, everything())
weather_df
```


## `group_by`

```{r}
weather_df %>% 
  group_by(name,month)
```

```{r}
weather_df %>%
  group_by(name) %>%
  summarize(n_obs = n())


weather_df %>%
  group_by(month) %>%
  summarize(n_obs = n())

weather_df %>%
  group_by(name,month) %>%
  summarize(n_obs = n())
```



```{r}

weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_unique = n_distinct(date)) #distinct date
```

```{r}

weather_df %>%
  count(name)  #count unique name   count = group_by + summarize

weather_df %>%
  count(month,name = "n_days") 

weather_df %>%
  count(name,month) 

```


```{r}
weather_df %>% 
  pull(name) %>% 
  table()  # hard to do addition work
```


```{r}
weather_df %>% 
  count(name) %>%
  knitr::kable()
```

## (2 x 2 table)
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~"cold",
      tmax >= 5~ "not cold",
      TRUE  ~""   #anything else
    )
  ) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name,cold) %>% 
  summarize(
    n_obs = n()
  ) %>% 
  pivot_wider(
    names_from = cold, 
    values_from = n_obs)
  
```



```{r}

weather_df %>% 
  mutate(cold = case_when(
    tmax < 5 ~ "cold",
    tmax >=5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```


## gerneral summarize

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(
    n = n(),
    mean_tmax = mean(tmax,na.rm = TRUE),  #remove na
    sd_tmax = sd(tmax,na.rm = TRUE),
    median_prcp = median(prcp,na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point() + geom_line() 
  

```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```

## don't forget ungroup??
```{r}
weather_df %>% 
  group_by(name) %>% 
  ungroup()
 #return to a non-grouped form
```

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax,na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes( x = date, y = centered_tmax,color = name))+
  geom_point()
```

window functions in grouped mutates
```{r}
weather_df %>% 
  group_by(name,month) %>% 
  mutate(
    tmax_rank = min_rank(tmax)
  ) %>% 
  filter(tmax_rank == 1)
```

lags and leads

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax),  # off by one 
    one_day_tmax_change = tmax - lagged_tmax
  ) %>% 
summarize(
 sd_daily_change = sd(one_day_tmax_change,na.rm = TRUE)
)
```


```{r}

```

