---
title: "Visualization"
author: "Weijia Xiong"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),  # download weather data
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```


```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```


```{r}
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()

```

#advanced scatterplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))


weather_df %>% 
  ggplot(aes(x = tmin,y = tmax)) +
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)


weather_df %>% 
  ggplot(aes(x = tmin,y = tmax, color = name)) +  # smooth for each color
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE)

           
```

```{r}

weather_df %>% 
  ggplot(aes(x = tmin,y = tmax, color = name)) +  # smooth for each color
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE)+
  facet_grid(.~name)

          
weather_df %>% 
  ggplot(aes(x = date,y = tmax, color = name)) +  # smooth for each color
  geom_point(aes(size = prcp),alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(.~name)
```


```{r}

# no point
weather_df %>% 
  ggplot(aes(x = date,y = tmax, color = name)) +  # smooth for each color
  geom_smooth(se = FALSE) 


       
weather_df %>% 
  ggplot(aes(x = date,y = tmax, color = name)) +  # smooth for each color
  geom_point(aes(size = prcp),alpha = .5) +
  geom_smooth(size = 3, se = FALSE)


```

## Learning assessment
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(tmax_fahr = tmax * (9 / 5) + 32,
         tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)

```


## 2d density

```{r}
       
weather_df %>% 
  ggplot(aes(x = tmin,y = tmax)) +
  geom_hex()

     
weather_df %>% 
  ggplot(aes(x = tmin,y = tmax)) +
  geom_bin2d()
```

## More kind of plots

## histogram
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +  ## color : shade
  geom_histogram(position = "dodge", binwidth = 3)   #seperate bars
  

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +  ## color : shade
  geom_histogram() +
  facet_grid(.~name)


weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +  ## color : shade
  geom_histogram() +
  facet_grid(name~.)
  
```

## density plot
```{r}

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +  ## color : shade
  geom_density(alpha = .3)   
  
```

## box plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```

## violin plot: see the distribution 
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```

## ridge plots
```{r}
# compare density in each group
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

